apiVersion: batch/v1
kind: Job
metadata:
#  generateName: migrate-database-job-
  name: migrate-database-job
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: pre-check
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - echo "🔍 Eseguo migrazione del database..."; sleep 2; echo "✅ Migrazione completata."