apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0 # Numero massimo di Pod che possono essere non disponibili durante un aggiornamento
      maxSurge: 1 # Numero massimo di Pod che possono essere creati oltre il numero desiderato di Pod durante un aggiornamento
    type: RollingUpdate # Tipo di strategia di aggiornamento (RollingUpdate)
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9797"
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: stefanprodan/podinfo:6.9.0
          command:
            - ./podinfo
            - --port=9898
            - --port-metrics=9797
            - --grpc-port=9999
            - --grpc-service-name=backend
            - --level=info
          ports:
            - name: http
              containerPort: 9898
              protocol: TCP
            - name: http-metrics
              containerPort: 9797
              protocol: TCP
            - name: grpc
              containerPort: 9999
              protocol: TCP
          env:
            - name: PODINFO_UI_COLOR
              value: "#03A9F4"
            - name: PODINFO_UI_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: PODINFO_UI_MESSAGE
          livenessProbe:
            exec:
              command:
                - podcli
                - check
                - http
                - localhost:9898/healthz
            initialDelaySeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - podcli
                - check
                - http
                - localhost:9898/readyz
            initialDelaySeconds: 5
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 1000m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 32M
