apiVersion: v1
kind: Service
metadata:
  name: backend
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    # ArgoCD UI links principali
    link.argocd.argoproj.io/external-link: "http://localhost:30072"
    link.argocd.argoproj.io/health: "http://localhost:30072/healthz"
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - name: http
      port: 8080
      targetPort: 9898
      nodePort: 30072
