apiVersion: v1
kind: Service
metadata:
  name: frontend
  annotations:
    # ArgoCD UI links principali
    argocd.argoproj.io/external-link: "http://localhost:30071"
    link.argocd.argoproj.io/external-link: "http://localhost:30071"
    # Link aggiuntivi con categorie
    link.argocd.argoproj.io/health: "http://localhost:30071/healthz"
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 9898
